### PR TITLE
Make I2S examples work on ESP32

### PR DESCRIPTION
**Pull request by bjoernQ**
- avoid using ESP32 UART pins
- don't use MCLK in RX examples
- don't try to use MCLK for ESP32 in TX examples

### CODE REVIEW

**Review by JurajSadel — APPROVED** [review]
Besides that ugly clippy thing, LGTM.

**Comment by bjoernQ** [comment]
> Besides that ugly clippy thing, LGTM.

Oh wow - ICE in Clippy

**Comment by bjoernQ** [comment]
No idea what to do about the ICE 🤔 I think it's triggered by src/tools/clippy/clippy_lints/src/doc/needless_doctest_main.rs

**Comment by jessebraham** [comment]
> No idea what to do about the ICE 🤔 I think it's triggered by src/tools/clippy/clippy_lints/src/doc/needless_doctest_main.rs

This looks fine otherwise, we can just ignore it for today. Hopefully tomorrow's nightly is fixed.

**Review by jessebraham — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
